p8105_hw2_hg2596
================
2022-10-06

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)
library(dplyr)
library(readr)
```

# Problem 2

# Import Mr.Trash Wheel

``` r
mtw = read_excel("./data/Trash_Wheel_Collection_Data.xlsx", sheet = "Mr_Trash_Wheel") 
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

# Clean data for Mr.Trash Wheel

``` r
mtw_2 = read_excel("./data/Trash_Wheel_Collection_Data.xlsx", sheet = "Mr_Trash_Wheel",range = cell_cols("A:N"), col_names = TRUE, col_types = NULL, trim_ws = TRUE,skip = 1, n_max = 535) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>%
  mutate(dumpster = as.character(dumpster)) %>%
  mutate(year = as.character(year)) %>%
  mutate(sports_balls = as.integer(sports_balls)) %>%
  mutate(marker = 1) %>%
  select(dumpster,marker,everything())
```

# Import Professor Trash Wheel

``` r
ptw = read_excel("./data/Trash_Wheel_Collection_Data.xlsx", sheet = "Professor_Trash_Wheel") 
```

# Clean data for Professor Trash Wheel

``` r
ptw_2 = read_excel("./data/Trash_Wheel_Collection_Data.xlsx", sheet = "Professor_Trash_Wheel", range = cell_cols("A:M"), col_names = TRUE, col_types = NULL, trim_ws = TRUE,skip = 1, n_max = 115) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(month)) %>%
  drop_na(dumpster)%>%
  mutate(dumpster = as.character(dumpster)) %>%
  mutate(year = as.character(year)) %>%
  mutate(marker = 2) %>%
  select(dumpster,marker,everything())
```

# Merge through joint

``` r
merge = bind_rows(mtw_2,ptw_2) 
```

# Find Professor Trash Wheel Weight of trash

``` r
merge %>%
  filter(marker == 2) %>%
  pull(weight_tons) %>%
  sum(na.rm = TRUE) 
```

    ## [1] 190.12

# Find sum of sports balls

``` r
merge %>%
  filter(year == 2020) %>%
  pull(sports_balls) %>%
  sum(na.rm = TRUE) 
```

    ## [1] 856

This new dataset has 641 observations and 15 variables. Some key
variables are **dumpster**, **month**, **date**, **year**,
**weight(tons)**,**sports balls** and various other trash items. The
**marker** variable is too help keep track of each dataset, “1”
indicates it came from Mr.Trash Wheel dataset and “2” indicates it came
from Professor Trash Wheel dataset.

The total weight of trash collected in Professor Trash Wheel is 190.12
tons.\`

Also, the total number of sport balls 856.
